<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CityRegion;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * CityRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRegionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $cityId
     * @return int|null
     */
    public function getRegionIdByCityId(int $cityId): ?int
    {
        $qb = $this->createQueryBuilder('cr')
            ->where('cr.cityId = :cityId')
            ->setParameter('cityId', $cityId)
            ->setMaxResults(1);

        try {
            /** @var CityRegion $cityRegion */
            $cityRegion = $qb->getQuery()->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        } catch (NonUniqueResultException $e) {
            return null;
        }

        return $cityRegion->getRegionId();
    }
}
