# Learn more about filters
# https://api-platform.com/docs/core/filters
services:
    # configure filters
    #foo.search_filter:
    #    parent: 'api_platform.doctrine.orm.search_filter'
    #    arguments: [ { id: 'exact', bar: 'partial' } ]
    #    tags: ['api_platform.filter']
    api-platform.boolean_filter:
        parent: 'api_platform.doctrine.orm.boolean_filter'
        tags: ['api_platform.filter']
    api-platform.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        tags: [ 'api_platform.filter' ]
    api-platform.date_filter:
        parent: 'api_platform.doctrine.orm.date_filter'
        tags:  [ 'api_platform.filter' ]
