fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api:
    resource: '.'
    type: 'api_platform'
    prefix: '/api/v3'

app:
    resource: '@AppBundle/Action/'
    type: 'annotation'

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /api/v3/docs
        permanent: true