security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_READER: ROLE_USER
        ROLE_MANAGER: ROLE_READER
        ROLE_ADMIN: ROLE_MANAGER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        main:
            pattern:   ^/
            provider: fos_userbundle
            stateless: true
            anonymous: true
            #lexik_jwt: ~
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Public API
        - { path: ^/api/v3/docs, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v3/hotel-views, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/v3/hotel-map, role: IS_AUTHENTICATED_ANONYMOUSLY}

        # Каталог отелей
        - { path: ^/api/v3/hotels-catalog/filters-data, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/v3/hotels-catalog/hotels-counters, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/v3/hotels-catalog/search, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/v3/mobile/hotels-catalog/search, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/v3/mobile/hotel-by-deal-offer, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v3/active-deal-offers, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v3/mobile/hotel-views-by-deal-offer, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v3/catalog, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/auth-check, role: [ROLE_USER] }

        - { path: ^/api, role: [ROLE_READER] }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
